In [13]:
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import pandas as pd

uri = "mongodb+srv://omarvasquezchavarri_db_user:RwkM6HHQVMwVERCt@cluster0.oygyxla.mongodb.net/?appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [50]:
import sqlalchemy as db
import pandas as pd
engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3310/retail_db')
con = engine.connect()

df_departamets = pd.read_sql_table('departments',con=con)
df_departamets

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [4]:
dbName = client['retail_db']

In [5]:
df_departamets

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [6]:
df_to_dict = df_departamets.to_dict('records')

In [7]:
df_to_dict

[{'department_id': 2, 'department_name': 'Fitness'},
 {'department_id': 3, 'department_name': 'Footwear'},
 {'department_id': 4, 'department_name': 'Apparel'},
 {'department_id': 5, 'department_name': 'Golf'},
 {'department_id': 6, 'department_name': 'Outdoors'},
 {'department_id': 7, 'department_name': 'Fan Shop'}]

In [8]:
#escribir en mongo
dbName['department'].insert_many(df_to_dict)

InsertManyResult([ObjectId('6a383424b8fd0289aaf09d5b'), ObjectId('6a383424b8fd0289aaf09d5c'), ObjectId('6a383424b8fd0289aaf09d5d'), ObjectId('6a383424b8fd0289aaf09d5e'), ObjectId('6a383424b8fd0289aaf09d5f'), ObjectId('6a383424b8fd0289aaf09d60')], acknowledged=True)

In [18]:
department = dbName['department'].find({})

In [19]:
df_department2 = pd.DataFrame(department)
df_department2

                        _id  department_id department_name
0  6a383424b8fd0289aaf09d5b              2         Fitness
1  6a383424b8fd0289aaf09d5c              3        Footwear
2  6a383424b8fd0289aaf09d5d              4         Apparel
3  6a383424b8fd0289aaf09d5e              5            Golf
4  6a383424b8fd0289aaf09d5f              6        Outdoors
5  6a383424b8fd0289aaf09d60              7        Fan Shop
6  6a3837403fd51ffd4f426759              8       SportWear

In [35]:
df_department2

                     id_row  department_id department_name
0  6a383424b8fd0289aaf09d5b              2         Fitness
1  6a383424b8fd0289aaf09d5c              3        Footwear
2  6a383424b8fd0289aaf09d5d              4         Apparel
3  6a383424b8fd0289aaf09d5e              5            Golf
4  6a383424b8fd0289aaf09d5f              6        Outdoors
5  6a383424b8fd0289aaf09d60              7        Fan Shop
6  6a3837403fd51ffd4f426759              8       SportWear

In [31]:
df_department2.rename(columns={'_id': 'id_row'}, inplace=True)

In [40]:
df_c = pd.DataFrame(df_department2)

In [43]:
df_c[['department_id','department_name']]

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
6              8       SportWear

In [48]:
df_department2[['department_id','department_name']].to_sql('Department_db', con=con, index=False, if_exists='append')

7

In [51]:
Department_db = pd.read_sql_table('Department_db', con=con)

In [52]:
Department_db

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop
6              8       SportWear