In [38]:
import pandas as pd

In [39]:
path = '../session2/data_retail'

path_customers = f'{path}/customers'
path_orders = f'{path}/orders'
path_order_items = f'{path}/order_items'
path_products = f'{path}/products'
path_categories = f'{path}/categories'
path_departments = f'{path}/departments'

In [40]:
df_customers = pd.read_csv(path_customers,sep='|', header=None)
df_orders = pd.read_csv(path_orders,sep='|', header=None)
df_order_items = pd.read_csv(path_order_items,sep='|', header=None)
df_products = pd.read_csv(path_products,sep='|', header=None)
df_categories = pd.read_csv(path_categories,sep='|', header=None, names=['id_categories','id_grupo_categories','desc_categories'])
df_departments = pd.read_csv(path_departments,sep='|', header=None)

In [43]:
df_departments.columns =['id_department','desc_deparment']

In [44]:
df_departments

   id_department desc_deparment
0              2        Fitness
1              3       Footwear
2              4        Apparel
3              5           Golf
4              6       Outdoors
5              7       Fan Shop

In [31]:
df_categories.head()

   id_categorie  id_grupo_Categoria       desc_categoria
0             1                   2             Football
1             2                   2               Soccer
2             3                   2  Baseball & Softball
3             4                   2           Basketball
4             5                   2             Lacrosse

In [ ]:
#cambiar nombres de columnas
df_categories.columns = ['id_categorie','id_grupo_Categoria','desc_categoria']

In [32]:
df_categories.head()

   id_categorie  id_grupo_Categoria       desc_categoria
0             1                   2             Football
1             2                   2               Soccer
2             3                   2  Baseball & Softball
3             4                   2           Basketball
4             5                   2             Lacrosse

In [45]:
#df_departments
df_departments['desc_deparment'].duplicated().any()

np.False_

In [58]:
def validar_department(df, columaName):
    if df[columaName].duplicated().any():
        print(f'Hay departamentos duplicados en el dataframe en la columna {columaName}')
        exit(1)
    else:
        print(f'No existen duplicados')

#validar_department(df_departments,'desc_deparment')
validar_department(df_categories,'id_grupo_categories')

Hay departamentos duplicados en el dataframe en la columna id_grupo_categories

In [62]:
idValidos = set(df_departments['id_department'])
idValidos

{2, 3, 4, 5, 6, 7}

In [67]:
df_categories['id_grupo_categories'].isin(idValidos).all()
#any() hay uno verdadero?
#all() todos son verdadedos?

np.False_

In [69]:
df_departments.merge(df_categories,left_on='id_department', right_on='id_grupo_categories', how='left')

,id_department,desc_deparment,id_categories,id_grupo_categories,desc_categories
0,2,Fitness,1,2,Football
1,2,Fitness,2,2,Soccer
2,2,Fitness,3,2,Baseball & Softball
3,2,Fitness,4,2,Basketball
4,2,Fitness,5,2,Lacrosse
5,2,Fitness,6,2,Tennis & Racquet
6,2,Fitness,7,2,Hockey
7,2,Fitness,8,2,More Sports
8,3,Footwear,9,3,Cardio Equipment
9,3,Footwear,10,3,Strength Training
10,3,Footwear,11,3,Fitness Accessories
11,3,Footwear,12,3,Boxing & MMA
12,3,Footwear,13,3,Electronics
13,3,Footwear,14,3,Yoga & Pilates
14,3,Footwear,15,3,Training by Sport
15,3,Footwear,16,3,As Seen on TV!
16,4,Apparel,17,4,Cleats
17,4,Apparel,18,4,Men's Footwear
18,4,Apparel,19,4,Women's Footwear
19,4,Apparel,20,4,Kids' Footwear
20,4,Apparel,21,4,Featured Shops
21,4,Apparel,22,4,Accessories
22,5,Golf,23,5,Men's Apparel
23,5,Golf,24,5,Women's Apparel
24,5,Golf,25,5,Boys' Apparel
25,5,Golf,26,5,Girls' Apparel
26,5,Golf,27,5,Accessories
27,5,Golf,28,5,Top Brands
28,5,Golf,29,5,Shop By Sport
29,6,Outdoors,30,6,Men's Golf Clubs
30,6,Outdoors,31,6,Women's Golf Clubs
31,6,Outdoors,32,6,Golf Apparel
32,6,Outdoors,33,6,Golf Shoes
33,6,Outdoors,34,6,Golf Bags & Carts
34,6,Outdoors,35,6,Golf Gloves
35,6,Outdoors,36,6,Golf Balls
36,6,Outdoors,37,6,Electronics
37,6,Outdoors,38,6,Kids' Golf Clubs
38,6,Outdoors,39,6,Team Shop
39,6,Outdoors,40,6,Accessories
40,6,Outdoors,41,6,Trade-In
41,7,Fan Shop,42,7,Bike & Skate Shop
42,7,Fan Shop,43,7,Camping & Hiking
43,7,Fan Shop,44,7,Hunting & Shooting
44,7,Fan Shop,45,7,Fishing
45,7,Fan Shop,46,7,Indoor/Outdoor Games
46,7,Fan Shop,47,7,Boating
47,7,Fan Shop,48,7,Water Sports

In [72]:
#cuando las llaves primaria y la llave forania tiene el mismo nombre, se puede usar este query
df_departments.merge(df_categories,on=['id_department','id_grupo_categories'], how='left')

KeyError: 'id_department'

In [73]:
#escribir datos en planos
df_departments.to_csv('df_deparments.csv', index=False)

In [74]:
df_departments.to_json('df_deparments.json', orient='records', indent=4)

In [75]:
#escribir en base de datos
import sqlalchemy as db
import pandas as pd
engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3310/retail_db')
con = engine.connect()

In [76]:
df_departments.to_sql('departments_2', con=con, index=False)

6

In [79]:
df_prueba = pd.read_sql_table('departments_2',con=con)

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

In [78]:
df_prueba

   id_department desc_deparment
0              2        Fitness
1              3       Footwear
2              4        Apparel
3              5           Golf
4              6       Outdoors
5              7       Fan Shop