In [1]:
#escribir en base de datos
import sqlalchemy as db
import pandas as pd
engine = db.create_engine('mysql+mysqlconnector://root:root@localhost:3310/retail_db')
con = engine.connect()

In [7]:
df_customers = pd.read_sql_table('customers', con=con)
df_products = pd.read_sql_table('products', con=con)

In [5]:
df_customers['customer_id'].nunique()

12435

In [6]:
df_customers['customer_state'].value_counts()

customer_state
PR    4771
CA    2012
NY     775
TX     635
IL     523
FL     374
OH     276
PA     261
MI     254
NJ     219
AZ     213
GA     169
MD     164
NC     150
VA     136
CO     122
OR     119
MA     113
TN     104
NV     103
MO      92
HI      87
NM      73
CT      73
WA      72
UT      69
WI      64
LA      63
DC      42
SC      41
IN      40
MN      39
KY      35
KS      29
DE      23
OK      19
WV      16
RI      15
ND      14
AR      12
ID       9
MT       7
IA       5
AL       3
Name: count, dtype: int64

In [10]:
df_products.head()

,product_id,product_category_id,product_name,product_description,product_price,product_image
0,1,2,Quest Q64 10 FT. x 10 FT. Slant Leg Instant U,,59.98,http://images.acmesports.sports/Quest+Q64+10+F...
1,2,2,Under Armour Men's Highlight MC Football Clea,,129.99,http://images.acmesports.sports/Under+Armour+M...
2,3,2,Under Armour Men's Renegade D Mid Football Cl,,89.99,http://images.acmesports.sports/Under+Armour+M...
3,4,2,Under Armour Men's Renegade D Mid Football Cl,,89.99,http://images.acmesports.sports/Under+Armour+M...
4,5,2,Riddell Youth Revolution Speed Custom Footbal,,199.99,http://images.acmesports.sports/Riddell+Youth+...

In [ ]:
#Precio maximo y minimo de productos
#df_products['product_price'].idxmax()
df_products['product_price'].idxmin()

37

In [24]:
#df_products.nlargest(10,'product_price')
df_products.nsmallest(10,'product_price')

,product_id,product_category_id,product_name,product_description,product_price,product_image
37,38,3,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
387,388,18,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
413,414,19,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
516,517,24,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
546,547,25,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
933,934,42,Callaway X Hot Driver,,0.00,http://images.acmesports.sports/Callaway+X+Hot...
1283,1284,57,Nike Men's Hypervenom Phantom Premium FG Socc,,0.00,http://images.acmesports.sports/Nike+Men%27s+H...
623,624,29,adidas Batting Helmet Hardware Kit,,4.99,http://images.acmesports.sports/adidas+Batting...
814,815,37,Zero Friction Practice Golf Balls - 12 Pack,,4.99,http://images.acmesports.sports/Zero+Friction+...
335,336,15,"Nike Swoosh Headband - 2""",,5.00,http://images.acmesports.sports/Nike+Swoosh+He...

In [18]:
df_products.loc[:,['product_name','product_price']].sort_values(by='product_price',ascending=True).head()

                                       product_name  product_price
413   Nike Men's Hypervenom Phantom Premium FG Socc            0.0
933                           Callaway X Hot Driver            0.0
516   Nike Men's Hypervenom Phantom Premium FG Socc            0.0
387   Nike Men's Hypervenom Phantom Premium FG Socc            0.0
1283  Nike Men's Hypervenom Phantom Premium FG Socc            0.0

In [13]:
df_products.sort_values(by='product_price',ascending=False).head()

,product_id,product_category_id,product_name,product_description,product_price,product_image
207,208,10,SOLE E35 Elliptical,,1999.99,http://images.acmesports.sports/SOLE+E35+Ellip...
198,199,10,SOLE F85 Treadmill,,1799.99,http://images.acmesports.sports/SOLE+F85+Tread...
65,66,4,SOLE F85 Treadmill,,1799.99,http://images.acmesports.sports/SOLE+F85+Tread...
495,496,22,SOLE F85 Treadmill,,1799.99,http://images.acmesports.sports/SOLE+F85+Tread...
1047,1048,47,"Spalding Beast 60"" Glass Portable Basketball",,1099.99,http://images.acmesports.sports/Spalding+Beast...